### ISSUE TITLE
/login endpoint

### ISSUE THREAD

**Issue by vinh-tranhuu** [210419-USF-BSN-Java/Kemo-Allen#1]
I cloned it onto my device, ran it on VSCode and it worked for me.
![image](https://user-images.githubusercontent.com/72952774/118724231-f6c56680-b7f3-11eb-903a-742b7a562c88.png)

I had some issues with the web.xml so I used this: 
![image](https://user-images.githubusercontent.com/72952774/118724464-4441d380-b7f4-11eb-8d79-7c83776a3b05.png)

**Comment by vinh-tranhuu** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://java.sun.com/xml/ns/javaee" xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd" version="2.5">

For copy and paste purposes.

**Comment by vinh-tranhuu** [comment]
?xml version="1.0" encoding="UTF-8"?

web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://java.sun.com/xml/ns/javaee" xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd" version="2.5"

Try this and readd the tags

**Comment by Kallen15** [comment]
I'm getting some errors now. Earlier it seemed that the app and sts were not communicating, so at least there is some feedback now.

**Comment by Kallen15** [comment]
It's working now. I just had to clean and update. So it was something in the web.xml that was giving the issue. Thanks Kevin.
